import json
import board

DEFAULT_LAYOUT_KEY = "DEFAULT"
ROW_PINS    = [board.GP0]
COLUMN_PINS = [board.GP1, board.GP2, board.GP12, board.GP13, board.GP14, board.GP15]

MEMORY_SIZE = 16

MEMORY_ADDRESS = 80
DISPLAY_ADDRESS = 60

SAVED_KEY_PRESSED_FIRST_BIT = 0
SAVED_KEY_PRESSED_LENGTH = 6

SAVED_GAME_SCORE_FIRST_BIT = SAVED_KEY_PRESSED_FIRST_BIT + SAVED_KEY_PRESSED_LENGTH
SAVED_GAME_SCORE_LENGTH = 6


DISPLAY_WIDTH = 128
DISPLAY_HEIGHT = 32
EXTERNAL_SCL = board.GP5
EXTERNAL_SDA = board.GP4
SECOND_PART_TX = board.GP4
SECOND_PART_RX = board.GP9
DISPLAY_COLOR = 0xFFFFFF

SHOW_GAME_BUTTON = "SHOW_GAME"
DISABLE_DISPLAY_BUTTON = "DISABLE_DISPLAY"
